import json
import os
import base64
from PIL import Image
from PIL.PngImagePlugin import PngInfo

def generate_character_card_v2(character_name: str, core_system_prompt: str, extracted_details: dict) -> dict:
    """
    Formats extracted data into a strictly compliant Character Card V2 JSON object.
    Injects Anachronism Guardrails into the system prompt.
    """
    guardrails = extracted_details.get("anachronism_guardrails", [])

    # Inject guardrails into system prompt
    system_prompt = core_system_prompt
    if guardrails:
        if isinstance(guardrails, list):
            guardrails_str = ", ".join(str(g) for g in guardrails)
        else:
            guardrails_str = str(guardrails)

        system_prompt += f"\n\nAnachronism Guardrails (DO NOT reference these): {guardrails_str}"

    description = extracted_details.get("description", "")
    personality = extracted_details.get("personality", "")
    scenario = extracted_details.get("scenario", "")
    mes_example = extracted_details.get("mes_example", "")

    if isinstance(personality, list):
        personality = ", ".join(str(p) for p in personality)

    # V2 Spec Root Object
    card_v2 = {
        "spec": "chara_card_v2",
        "spec_version": "2.0",
        "data": {
            "name": character_name,
            "description": description,
            "personality": personality,
            "scenario": scenario,
            "first_mes": "", # You could add a first message generation if wanted
            "mes_example": mes_example,
            "creator_notes": "Generated by PersonaForge",
            "system_prompt": system_prompt,
            "post_history_instructions": "",
            "tags": [],
            "creator": "PersonaForge",
            "character_version": "1.0",
            "alternate_greetings": [],
            "extensions": {}
        }
    }
    return card_v2

def generate_lorebook(entities: list[dict]) -> dict:
    """
    Formats the extracted world entities into a Lorebook JSON format.
    """
    entries = []

    for i, entity in enumerate(entities):
        key = entity.get("key", "")
        content = entity.get("content", "")

        # Standard lorebook structure (e.g., Tavern/SillyTavern compatible)
        entries.append({
            "uid": i + 1,
            "key": [key] if isinstance(key, str) else key,
            "keysecondary": [],
            "comment": "",
            "content": content,
            "constant": False,
            "vectorized": False,
            "selective": True,
            "order": 100,
            "position": 0,
            "disable": False
        })

    lorebook = {
        "entries": entries
    }

    return lorebook

def export_character_data(character_name: str, card_v2: dict, lorebook: dict, output_dir: str = ".") -> tuple[str, str]:
    """
    Saves the Character Card V2 and Lorebook as JSON files.
    """
    # Sanitize character name for filename
    safe_name = "".join([c if c.isalnum() else "_" for c in character_name]).strip("_").lower()

    card_filepath = os.path.join(output_dir, f"{safe_name}.json")
    lorebook_filepath = os.path.join(output_dir, f"{safe_name}_lorebook.json")

    with open(card_filepath, 'w', encoding='utf-8') as f:
        json.dump(card_v2, f, indent=4, ensure_ascii=False)

    with open(lorebook_filepath, 'w', encoding='utf-8') as f:
        json.dump(lorebook, f, indent=4, ensure_ascii=False)

    return card_filepath, lorebook_filepath

def embed_v2_in_png(card_v2: dict, image_path: str, output_path: str):
    """
    Embeds the Character Card V2 JSON data into the EXIF/tEXt metadata of a PNG file.
    Specifically using the 'chara' keyword standard for V2 PNGs.
    """
    if not os.path.exists(image_path):
        raise FileNotFoundError(f"Source image {image_path} not found.")

    # Serialize JSON
    json_data = json.dumps(card_v2)
    # Convert to base64
    b64_data = base64.b64encode(json_data.encode('utf-8')).decode('utf-8')

    image = Image.open(image_path)
    metadata = PngInfo()

    # Copy existing metadata
    for k, v in image.info.items():
        if isinstance(v, str):
            metadata.add_text(k, v)

    # Add Character Card metadata
    metadata.add_text('chara', b64_data)

    image.save(output_path, "PNG", pnginfo=metadata)
